//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Resources;

[assembly: AssemblyCompany("Kent Boogaart")]
[assembly: AssemblyProduct("Genesis.Join")]
[assembly: AssemblyVersion("2.0.1.0")]
[assembly: AssemblyFileVersion("2.0.1.0")]
[assembly: AssemblyInformationalVersion("2.0.1")]
[assembly: AssemblyCopyright("© Copyright. Kent Boogaart.")]
[assembly: AssemblyConfiguration("Release")]

// Custom Attributes
[assembly: NeutralResourcesLanguage("en-US")]
